// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import { ReactNode } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,1,200" />
      </head>
      <body className={"flex justify-center items-center font-mono m-20"}>{children}</body>
    </html>
  );
}
